### ISSUE TITLE
Name appears as "Unknown Actor" and portrait still appears when styling is disabled

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#40]
### Environment Details

* Foundry VTT Version: (Example 0.8.8)
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: dnd5e
* Modules Enabled?: no

### Issue Description

If you disable the styling for certain chats (e.g. by setting the "Display setting" to "none"), then the portrait still appears and the speaker is displayed as "Unknown Actor"... 
![image](https://user-images.githubusercontent.com/898086/123871886-3079a900-d92c-11eb-8a95-fb2d4327b97a.png)

**Comment by p4535992** [comment]
Should be fixed in 0.2.14 version

**Comment by p4535992** [comment]
Not sure 100% let me know if you find some problem

**Comment by cs96and** [comment]
It no longer displays "Unknown Actor", but is still adding the styling to the cards.  E.g If I set the styling to none, I would not expect to see the portrait on any cards.  Or if I set the styling to "players", then there should be no styling on the GM's messages.

**Comment by p4535992** [comment]
aaaah. now i get it.
it's my fault, I will add a further module setting to manage the cases in which you want to activate the unknown feature or the styling

**Comment by p4535992** [comment]
Should be fixed in 0.2.15 version

**Comment by Wade0004** [comment]
I wasn't having this issue before, but after getting today's update I am.
FVTT 0.8.8
DND  1.3.6
Not sure if its another module battling with it???

![image](https://user-images.githubusercontent.com/74107522/124194973-bad62000-da86-11eb-8032-85d054962199.png)

**Comment by nickelpro** [comment]
This is chat portraits, by changing the "Display Unknown" setting to "None" you can get some portraits back but not all

**Comment by Wade0004** [comment]
Does that change the weapon too?

this is without the module:

![image](https://user-images.githubusercontent.com/74107522/124195314-6da67e00-da87-11eb-865d-f5149887f19b.png)


unchecked all other modules but this one and it didn't fix it:

![image](https://user-images.githubusercontent.com/74107522/124195101-f1ac3600-da86-11eb-871f-b196222f4cd8.png)

**Comment by Wade0004** [comment]
NVM, looks like you were right, toggled to "show unknown" to "none" and got some icons and names... TYVM: 

![image](https://user-images.githubusercontent.com/74107522/124195669-22d93600-da88-11eb-8e73-1c3a18528499.png)

**Comment by p4535992** [comment]
Unfortunately, the cause of this was my development oversight. I updated the readme.md file highlighting the problem. The solution as you discovered is to set the new module settings to differ when you want or not styling, or when you want the unknown feature or not.

**Comment by nickelpro** [comment]
Surely the default setting should be "None" here? Who would want every style to be set to the unknown portrait?

**Comment by p4535992** [comment]
Yea make sense fixed on 0.2.16

**Comment by p4535992** [comment]
Should be finally fixed from 0.3.0 and newer
